### ISSUE TITLE
¿Puede un familiar tener varios expedientes?

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/ServiciosSociales#1]
Yo creo que por hacerlo más sencillo un familiar solo puede estar relacionado con un expediente. Y creo que en la vida real también se hace así. Por ejemplo: cuando pido una beca tengo que poner los datos de mis hermanos, pero si mi hermano pide la misma beca, él también tendría que poner todos los datos de sus hermanos, a pesar de que ya están en el sistema.
@FelipeSulser

**Comment by FelipeSulser** [comment]
Hemos decidido que tu decisión es la correcta

**Comment by estebanpw** [comment]
Secundo la decisión.

Tuesday, 07 April
09 : 53 : 59
(GMT + 2:00)
