### ISSUE TITLE
¿Quién es Samuel Benavides?

### ISSUE THREAD

**Issue by estebanpw** [FelipeSulser/ServiciosSociales#14]
I think the title is self-explanatory.

**Comment by HaritzPuerto** [comment]
LOOOOOOL está todo aclarado. Faure esta tarde te lo explicará. Curiosamente es amigo mío. Te vas a reir un poco jajjajaja ㅋㅋㅋㅋㅋㅋ

**Comment by estebanpw** [comment]
si @AlvaroFaure está involved es que algo va mal.

**Comment by AlvaroFaure** [comment]
Bueno, pues resulta que el tal Samuel es un amigo de Haritz que no tiene ni puñetera idea de lo que hoy acaba de pasar, pero que sin embargo ha hecho commit de una modificación en un documento (Intervenciones.java) cambiando el autor de felipesulser a Grupo E.

Eso ha sido en torno a las 10 de la mañana, así que uno de nosotros (yo no, porque no he cambiado eso ni Haritz tampoco) ha commiteado ese cambio pero lo ha hecho desde la cuenta de este chico, que suponemos que se la habrá dejado puesta en alguno de los ordenadores.

Tenemos la teoría de que antes de Semana Santa usó github pero no cerró sesión y que Esteban esta mañana (o Felipe si ha usado github desde uno de los ordenadores del laboratorio) ha entrado en ella y se ha olvidado de iniciar sesión (¿porque ha entrado a través de un correo recibido?), conectándose a la cuenta de este chaval, modificando el .java desde la propia web y haciendo commit de eso.

Eso explicaría por qué está ahí. Pero puede haber sido cualquier cosa. El caso es que es una coincidencia tremenda.

Y como era larga de contar toda la historia pues os la he soltado yo.

**Comment by estebanpw** [comment]
LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL

podéis descartar que fui yo porque le enseñé a felipe mi foto de usuario para vacilarle

**Comment by HaritzPuerto** [comment]
Nope, creo que fuiste tú @steveomatic . Los cambios realizados con ese usuario los hiciste tú. Por lo menos me suena haberte visto cambiar alguna de esas cosas.
