### ISSUE TITLE
Vivienda actual es una relación entre expediente y vivienda

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/ServiciosSociales#18]
Cambiamos la versión. Antes era una relación con ciudadano pero daba problemas para crear un ciudadano. ADemás, @AlvaroFaure  y yo pensamos que tiene más sentido así

**Comment by steveomatic** [comment]
@HaritzPuerto 
Importante:
en el branch que estas trabajando hay un fallo en la clase Ciudadano, línea 44:
    @OneToMany(mappedBy="ciudadano") //esta en minuscula xd
    private List<Cita> citas;

Hay que poner:
    @OneToMany(mappedBy="Ciudadano") 
    private List<Cita> citas;

Si no, peta al crear la db.

**Comment by estebanpw** [comment]
@HaritzPuerto @AlvaroFaure 
Oye, creo que he encontrado un fallo. En VIVIENDA, en la relación OneToOne de Expediente a Vivienda:
@ OneToOne
    @JoinColumn(nullable = false)
    private Expediente expediente_residencia;

El nullable debería poder ser true, porque si no, NUNCA podrá haber una vivienda deshabitada, ¿O me equivoco?

**Comment by HaritzPuerto** [comment]
Lo cierro ya que se aceptó la PR
