### ISSUE TITLE
Ciudadano no está relacionado con expediente en el jpa

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/ServiciosSociales#20]

**Comment by estebanpw** [comment]
Un momento, en mi esquema si sale relacionado ya, mira:
Atributos de ciudadano: 
ID, APELLIDO1, APELLIDO2, DNI, FECHA_NACIMIENTO, NACIONALIDAD, NOMBRE, EXPEDIENTE_PERSONAL_ID
¿Qué está pasando? 

Ah y oye, del otro que no respondiste a esto:
Steve said:
(lo de las fk de profesional)
Aqui hay una cosa que no entiendo. ¿No esta bien asi? Para ver las citas de un profesional solo habria que hacer un join entre Profesional y Cita por la id. ¿Para que poner en la propia tabla de profesional las citas como fk?

**Comment by HaritzPuerto** [comment]
Creo que me había liado xDDD No respondí porque seguía mirándolo y al ver que estaba bien hice PR y se me pasó responderte sorry 미안해~

**Comment by estebanpw** [comment]
aaah menos mal xd, ya pensaba que estaba perdido del todo
