### ISSUE TITLE
Cita debe ser entidad débil

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/ServiciosSociales#24]
Eso no está reflejado ni en el ER ni en el JPA

**Comment by AlvaroFaure** [comment]
Ya lo he modificado en el E/R, cámbialo tú en el JPA.

**Comment by AlvaroFaure** [comment]
Ya está en Drive el E/R definitivo y su imagen. La dejo aquí también: https://lh3.googleusercontent.com/fh0HJQneHWwbdOjEzSK1oOLJNtV2eBxCHRLD7dBwQhMurJPE-y91Ws73QmiMfZ12lcGxnZMn=w1342-h547

**Comment by AlvaroFaure** [comment]
Ya está el modelo E/R definitivo y su captura de pantalla subidas al drive (y la captura está colocada en la wiki). Sólo queda actualizar el JPA acorde a eso.
