### ISSUE TITLE
¿Cómo crear weak entity en JPA?

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/ServiciosSociales#27]
@AlvaroFaure @steveomatic 
No es tan fácil, hacer una PK compuesta por id y las FK no vale ya que las FK son relaciones. Mirad los apuntes y lo veréis. Hay que preguntar al profesor.

**Comment by HaritzPuerto** [comment]
Podríamos usar https://docs.oracle.com/cd/E19798-01/821-1841/giqxy/ Orphan Removal
Si borramos cita, anotaciones también se borrarían.

**Comment by estebanpw** [comment]
He usado OrphanRemoval. 
Aun así, para que funcione cada vez que se borra hay que desactivar las constraints
