### ISSUE TITLE
Añadir orphanRemoval="true" a todas las relaciones que deberían ser weak

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/ServiciosSociales#29]
Así si borramos una cita, las anotaciones también se borrarían.

**Comment by estebanpw** [comment]
voy a ello

**Comment by estebanpw** [comment]
ya lo tengo listo, lo subo en cuanto termine de comer (habia que cambiar relaciones de sitio, revisadlo bien luego)
